const filterActionTypes = {
    DISPLAY_PRODUCTS: "DISPLAY_PRODUCTS",
    DISPLAY_CATEGORIES: "DISPLAY_CATEGORIES",
    SEARCH: "SEARCH",
    CATEGORY: "CATEGORY",
    SORT_BY_PRICE: "SORT_BY_PRICE",
    SORT_BY_RATING_RANGE: "SORT_BY_RATING_RANGE",
    CLEAR_FILTERS: "CLEAR_FILTERS",
    GET_PRODUCT_DETAILS: "GET_PRODUCT_DETAILS",
    SET_ORDER_LIST: "SET_ORDER_LIST",
}

const wishlistActionTypes = {
    DISPLAY_WISHLIST: "DISPLAY_WISHLIST",
    ADD_TO_WISHLIST: "ADD_TO_WISHLIST",
    REMOVE_FROM_WISHLIST: "REMOVE_FROM_WISHLIST",
}

const cartActionTypes = {
    DISPLAY_CART: "DISPLAY_CART",
    ADD_TO_CART: "ADD_TO_CART",
    REMOVE_FROM_CART: "REMOVE_FROM_CART",
    UPDATE_QUANTITY_IN_CART: "UPDATE_QUANTITY_IN_CART",
}

const addressActionTypes = {
    DISPLAY_ADDRESSES: "DISPLAY_ADDRESSES",
    SET_ADDRESS_DETAILS: "SET_ADDRESS_DETAILS",
    EDIT_ADDRESS_DETAILS: "EDIT_ADDRESS_DETAILS",
    ADD_NEW_ADDRESS: "ADD_NEW_ADDRESS",
    REMOVE_ADDRESS: "REMOVE_ADDRESS",
    RESET_ADDRESS_FORM: "RESET_ADDRESS_FORM",
    SHOW_ADDRESS_MODAL: "SHOW_ADDRESS_MODAL",
    SET_DUMMY_ADDRESS: "SET_DUMMY_ADDRESS",
    ZIPCODE_ERROR: "ZIPCODE_ERROR",
    MOBILE_ERROR: "MOBILE_ERROR",
    SET_SELECTED_ADDRESS_ID: "SET_SELECTED_ADDRESS_ID",
}

export {
    addressActionTypes,
    cartActionTypes,
    wishlistActionTypes,
    filterActionTypes
}